# Generated by Django 3.0.5 on 2020-04-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200404_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='photo',
            field=models.ImageField(default='photos/1200px-No_image_available.svg.png', upload_to='photos/'),
        ),
    ]
