# Generated by Django 3.0.5 on 2020-04-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20200406_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(default='media/photos/no-image.png', upload_to='photos/'),
        ),
    ]
